### PR TITLE
Add reduced round variations of chacha

### PR DESCRIPTION
**Pull request by midnight-wonderer**
Any comment on the PR?

### CODE REVIEW

**Comment by codahale** [comment]
I'd prefer to keep the existing behavior of `New` for backwards compatibility.

Could you add this as a new func? Thanks!

**Comment by midnight-wonderer** [comment]
@codahale I saw the commit where you rename the constructor function.
For backward compatibility did you mean function signature and not the name?
Does this works for you then?
NewChaCha8, NewXChaCha8, NewChaCha12, NewXChaCha12, NewChaCha20, NewXChaCha20
The golang way is to copy and keep the copied source I don't think it will break anything at this point.  
If not what is the way to go?

**Comment by codahale** [comment]
That reorganization was more than a year ago. At this point there are existing projects which depend on the current API, and it would be impolite to change it. While you're right that vendoring dependencies is recommended, this does not prevent transitive conflicts.

In terms of func names, I think `New` and `NewWithRounds` would be fine.

**Comment by midnight-wonderer** [comment]
Any other comment?

**Comment by codahale** [comment]
Like I said, I don't want to change the existing API, so `NewXChaCha` should stay the same, with perhaps `NewXChaChaWithRounds` being added. I'm sorry if that wasn't clear.

**Comment by midnight-wonderer** [comment]
Sorry my bad it actually clear in the first place but I just overlooked XChaCha.

**Comment by codahale** [comment]
Awesome! Thanks for all the work. It's much appreciated.

**Pull request merged**
